services:
  db:
    image: postgis/postgis:16-3.4-alpine
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: foodtruck
      POSTGRES_PASSWORD: foodtruck
      POSTGRES_DB: foodtruck
    ports:
      - "5432:5432"